### ISSUE TITLE
针对  PR 12 的继续讨论

### ISSUE THREAD

**Issue by unicornx** [aosp-riscv/libvpx#13]
我又看了一下 <https://github.com/aosp-riscv/libvpx/pull/12/>，感觉原来的实现不太对，特别是你用了 e64，感觉没有什么道理，这里逻辑上就是在拷贝 byte（e8),  我们优化一般只是要尽量实现并发即可，以 `vp8_copy_mem8x4_c()` 为例，代码如下，
```cpp
void vp8_copy_mem8x4_c(unsigned char *src, int src_stride, unsigned char *dst,
                       int dst_stride) {
  int r;

  for (r = 0; r < 4; ++r) {
    memcpy(dst, src, 8);

    src += src_stride;
    dst += dst_stride;
  }
}
```

我的理解是做 4 次操作，每次操作中从 src 向 dst 拷贝 8 个字节。此外 src/dst 向后分别步进 `src_stride`/`dst_stride`。优化点在于 memcpy，memcpy 默认如果不优化，就是内部循环 8 次，我们这用了 rvv 就是希望一次并行在内存之间复制 8 个。

我看了一下 neon 的操作，其实也是这个思路：
```cpp
void vp8_copy_mem8x4_neon(unsigned char *src, int src_stride,
                          unsigned char *dst, int dst_stride) {
  uint8x8_t vtmp;
  int r;

  for (r = 0; r < 4; ++r) {
    vtmp = vld1_u8(src);
    vst1_u8(dst, vtmp);
    src += src_stride;
    dst += dst_stride;
  }
}
```
它利用 neon 的 c intrinsic 函数  `vld1_u8()/vst1_u8()` 替换了 `memcpy()` 

所以我们在 rvv 中其实只要想办法替换到 `memcpy()` 就可以了。`memcpy()` 应该是 glibc 库中实现的，这些 mem/str 函数一般都会根据 ARCH 做优化，我没有看过 glibc 中是不是已经基于 rvv 做了优化，但我们这里也可以抛开 glibc 自己做优化，就和 arm 一样，这样就不用担心动态连接的 glibc 是否是 rvv 的优化版本了。
具体的 memcpy 的优化版本可以参考 android 里的 bionic 的 rvv 优化版本： https://android-review.googlesource.com/c/platform/bionic/+/2606625/2/libc/arch-riscv64/string/memcpy_vext.S
虽然是汇编，但反向改成 c 也是很简单的。而且如果是按照 e8 计算，rvv 又好像规定 VLEN 最小是 128 bit(不太确定，“The V vector extension requires Zvl128b.”？你可以看看 rvv spec 的 18. Standard Vector Extensions)，如果真是那样，那么感觉我们这里循环都不需要 :) 如果不能确保最小 128， 是不是也可以利用 LMUL 扩展一下 vector register 的宽度，实在不行就加上 loop，我没有仔细想过，具体你自己先看看吧。

**Comment by sunmin89** [comment]
我在Lichee RV上跑这段代码 vp8_copy_mem8x4_rvv 报错：
Illegal instruction

thead 最新的工具链，编译参数：
COPS = -g -mcpu=c906fdv  -march=rv64imafdcv0p7_zfh_xtheadc -mabi=lp64d -mtune=c906 -static

对了，这段代码到底在干嘛呀？把 src 的内容复制到 dst 中吗？

**Comment by unicornx** [comment]
> 我在Lichee RV上跑这段代码 vp8_copy_mem8x4_rvv 报错： Illegal instruction
> 
> thead 最新的工具链，编译参数： COPS = -g -mcpu=c906fdv -march=rv64imafdcv0p7_zfh_xtheadc -mabi=lp64d -mtune=c906 -static
> 
> 对了，这段代码到底在干嘛呀？把 src 的内容复制到 dst 中吗？

逻辑你看 c 的代码呀，很简单，你把 src/dst 各看成一个字节流，然后从低地址到高地址，循环 4 次，每次复制 8 个字节后各自步进 src_stride/dst_stride 个字节的偏移量。

**Comment by sunmin89** [comment]
> > 我在Lichee RV上跑这段代码 vp8_copy_mem8x4_rvv 报错： Illegal instruction
> > thead 最新的工具链，编译参数： COPS = -g -mcpu=c906fdv -march=rv64imafdcv0p7_zfh_xtheadc -mabi=lp64d -mtune=c906 -static
> > 对了，这段代码到底在干嘛呀？把 src 的内容复制到 dst 中吗？
> 
> 逻辑你看 c 的代码呀，很简单，你把 src/dst 各看成一个字节流，然后从低地址到高地址，循环 4 次，每次复制 8 个字节后各自步进 src_stride/dst_stride 个字节的偏移量。

感谢，确实不难，按照neon的逻辑 通过 rvv0.7.1 u8m1 实现，然后在 D1 上跑，性能比 c 差远了
https://paste.debian.net/1289648/

以 vp8_copy_mem8x4_rvv 为例， 我认为 Trumeet 的实现方式，似乎没有问题呀？

Neon 的逻辑是4个循环，每次处理8个八位数据，数据总量是4x8x8
他是一次性处理4个64位数据，数据总量是4x64

**Comment by unicornx** [comment]
> > > 我在Lichee RV上跑这段代码 vp8_copy_mem8x4_rvv 报错： Illegal instruction
> > > thead 最新的工具链，编译参数： COPS = -g -mcpu=c906fdv -march=rv64imafdcv0p7_zfh_xtheadc -mabi=lp64d -mtune=c906 -static
> > > 对了，这段代码到底在干嘛呀？把 src 的内容复制到 dst 中吗？
> > 
> > 
> > 逻辑你看 c 的代码呀，很简单，你把 src/dst 各看成一个字节流，然后从低地址到高地址，循环 4 次，每次复制 8 个字节后各自步进 src_stride/dst_stride 个字节的偏移量。
> 
> 感谢，确实不难，按照neon的逻辑 通过 rvv0.7.1 u8m1 实现，然后在 D1 上跑，性能比 c 差远了 https://paste.debian.net/1289648/
> 
> 以 vp8_copy_mem8x4_rvv 为例， 我认为 Trumeet 的实现方式，似乎没有问题呀？
> 
> Neon 的逻辑是4个循环，每次处理8个八位数据，数据总量是4x8x8 他是一次性处理4个64位数据，数据总量是4x64

嗯，Trumeet 的做法应该是可以的，我当时觉得这里只要按照 neon 的做法就可以了（unit stride），但 Trumeet 的做法采用 constant stride 的方式似乎速度更快。

@sunmin89 按照 neon 的逻辑 通过 rvv0.7.1 u8m1 实现，然后在 D1 上跑，性能比 c 的实现还差？这是什么道理，是 c 被 autovector 优化了么，还是 memcpy 函数内部做了什么优化? 另外你发的那个链接失效了，我打不开。

@Trumeet 你确认过按照你的优化实现，copy 出来的字节内容是正确的么，如果是这样，我觉得你的这个优化应该也是可以的。

**Comment by sunmin89** [comment]
> > > > 我在Lichee RV上跑这段代码 vp8_copy_mem8x4_rvv 报错： Illegal instruction
> > > > thead 最新的工具链，编译参数： COPS = -g -mcpu=c906fdv -march=rv64imafdcv0p7_zfh_xtheadc -mabi=lp64d -mtune=c906 -static
> > > > 对了，这段代码到底在干嘛呀？把 src 的内容复制到 dst 中吗？
> > > 
> > > 
> > > 逻辑你看 c 的代码呀，很简单，你把 src/dst 各看成一个字节流，然后从低地址到高地址，循环 4 次，每次复制 8 个字节后各自步进 src_stride/dst_stride 个字节的偏移量。
> > 
> > 
> > 感谢，确实不难，按照neon的逻辑 通过 rvv0.7.1 u8m1 实现，然后在 D1 上跑，性能比 c 差远了 https://paste.debian.net/1289648/
> > 以 vp8_copy_mem8x4_rvv 为例， 我认为 Trumeet 的实现方式，似乎没有问题呀？
> > Neon 的逻辑是4个循环，每次处理8个八位数据，数据总量是4x8x8 他是一次性处理4个64位数据，数据总量是4x64
> 
> 嗯，Trumeet 的做法应该是可以的，我当时觉得这里只要按照 neon 的做法就可以了，但 Trumeet 的做法似乎更加发挥了 rvv 的优势。
> 
> @sunmin89 按照 neon 的逻辑 通过 rvv0.7.1 u8m1 实现，然后在 D1 上跑，性能比 c 的实现还差？这是什么道理，是 c 被 autovector 优化了么，还是 memcpy 函数内部做了什么优化? 另外你发的那个链接失效了，我打不开。

是的，差了10来倍，我不确定 c 是否被 autovector 了， 发的链接被人删了，代码如下，大家看下我是不是哪里弄错了，

```
#include <stdio.h>
#include <limits.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include <riscv_vector.h>


#define ROUND_POWER_OF_TWO(value, n) (((value) + (1 << ((n)-1))) >> (n))

uint8_t* getDataUint8(const int len){
    uint8_t* data = (uint8_t *)malloc(len * sizeof(uint8_t));
    for(int i = 0 ; i < len; i++){
    	data[i] = (uint8_t) (i + 1);
    }
    return data;
}

void vp8_copy_mem8x4_rvv(unsigned char *src, int src_stride,
                         unsigned char *dst, int dst_stride) {
  size_t vl;
  // D1 Lichee RV can't recognize these instructions
  // vuint64m2_t v;
  // /* VL must be 4 because VLEN must be >= 128. Assume e64 is supported. */
  // vl =  vsetvl_e64m2(4);
  // v =  vlse64_v_u64m2((uint64_t *) src, src_stride, vl);
  // vsse64_v_u64m2((uint64_t *) dst, dst_stride, v, vl);

  vuint8m1_t vtmp;
  int r;
  vl = 8;
  for (r = 0; r < 4; ++r) {
    vtmp = vle8_v_u8m1(src, vl);
    vse8_v_u8m1(dst, vtmp, vl);
    src += src_stride;
    dst += dst_stride;
  }
}


  void vp8_copy_mem8x4_c(unsigned char *src, int src_stride, unsigned char *dst,
                       int dst_stride) {
  int r;

  for (r = 0; r < 4; ++r) {
    memcpy(dst, src, 8);

    src += src_stride;
    dst += dst_stride;
  }
}

void test_copy_mem(){
    int w=40,h=20;
    uint8_t *src = getDataUint8(w*h),*dst = getDataUint8(w*h);
    uint8_t *ref = getDataUint8(w*h);
    int stride = 7;
    // int loops = 1000000000;
    // int loops = 10000000;
    int loops = 10000000;
    for(int i = 0;i< loops;i++){
        //this routine spends 1.9s on Lichee RV
        // vp8_copy_mem8x4_c(src,stride,dst,stride);
        //this routine spends 19s on Lichee RV
        vp8_copy_mem8x4_rvv(src,stride,dst,stride);
    }
}

int main() {
    test_copy_mem();
    return 0;
}
```

**Comment by unicornx** [comment]
> > 嗯，Trumeet 的做法应该是可以的，我当时觉得这里只要按照 neon 的做法就可以了，但 Trumeet 的做法似乎更加发挥了 rvv 的优势。
> > @sunmin89 按照 neon 的逻辑 通过 rvv0.7.1 u8m1 实现，然后在 D1 上跑，性能比 c 的实现还差？这是什么道理，是 c 被 autovector 优化了么，还是 memcpy 函数内部做了什么优化? 另外你发的那个链接失效了，我打不开。
> 
> 是的，差了10来倍，我不确定 c 是否被 autovector 了， 发的链接被人删了，代码如下，大家看下我是不是哪里弄错了，
> 
> ```
> #include <stdio.h>
> #include <limits.h>
> #include <stdlib.h>
> #include <stdint.h>
> #include <stddef.h>
> #include <stdbool.h>
> #include <string.h>
> #include <math.h>
> #include <riscv_vector.h>
> 
> 
> #define ROUND_POWER_OF_TWO(value, n) (((value) + (1 << ((n)-1))) >> (n))
> 
> uint8_t* getDataUint8(const int len){
>     uint8_t* data = (uint8_t *)malloc(len * sizeof(uint8_t));
>     for(int i = 0 ; i < len; i++){
>     	data[i] = (uint8_t) (i + 1);
>     }
>     return data;
> }
> 
> void vp8_copy_mem8x4_rvv(unsigned char *src, int src_stride,
>                          unsigned char *dst, int dst_stride) {
>   size_t vl;
>   // D1 Lichee RV can't recognize these instructions
>   // vuint64m2_t v;
>   // /* VL must be 4 because VLEN must be >= 128. Assume e64 is supported. */
>   // vl =  vsetvl_e64m2(4);
>   // v =  vlse64_v_u64m2((uint64_t *) src, src_stride, vl);
>   // vsse64_v_u64m2((uint64_t *) dst, dst_stride, v, vl);
> 
>   vuint8m1_t vtmp;
>   int r;
>   vl = 8;
>   for (r = 0; r < 4; ++r) {
>     vtmp = vle8_v_u8m1(src, vl);
>     vse8_v_u8m1(dst, vtmp, vl);
>     src += src_stride;
>     dst += dst_stride;
>   }
> }
> 
> 
>   void vp8_copy_mem8x4_c(unsigned char *src, int src_stride, unsigned char *dst,
>                        int dst_stride) {
>   int r;
> 
>   for (r = 0; r < 4; ++r) {
>     memcpy(dst, src, 8);
> 
>     src += src_stride;
>     dst += dst_stride;
>   }
> }
> 
> void test_copy_mem(){
>     int w=40,h=20;
>     uint8_t *src = getDataUint8(w*h),*dst = getDataUint8(w*h);
>     uint8_t *ref = getDataUint8(w*h);
>     int stride = 7;
>     // int loops = 1000000000;
>     // int loops = 10000000;
>     int loops = 10000000;
>     for(int i = 0;i< loops;i++){
>         //this routine spends 1.9s on Lichee RV
>         // vp8_copy_mem8x4_c(src,stride,dst,stride);
>         //this routine spends 19s on Lichee RV
>         vp8_copy_mem8x4_rvv(src,stride,dst,stride);
>     }
> }
> 
> int main() {
>     test_copy_mem();
>     return 0;
> }
> ```

你怎么没有 setvl 就直接 load/store？

**Comment by Trumeet** [comment]
~~啊抱歉这两天一直在 RVSC 所以没看 GitHub~~

刚爬完了楼，主要是这样几点吧：

1. 用 e64 主要是为了减少循环，同时在 8x4 上完全避免循环。因为 8x4 是一共需要复制 `8 * 4 = 32 Bytes`，也就是 `32 * 8 = 256 bits`。由于使用 `__riscv_v[sl]se64_v_u64m2`，即 `EEW = SEW = 64 bits`。因为 `VLEN >= 128, LMUL = 2, SEW = 64, AVL = 4`，所以 `VL = min(AVL, VLMAX) = min(4, VLEN * LMUL / SEW) = min(4, 128 * 2 / 64) = min(4, 4) = 4`。这样每次访存即为 `VL * EEW = 4 * 64 bits = 256 bits = 32 Bytes`。因此一次访存可以处理 32 Bytes，一次性满足了 8x4 的需求，而对于 8x8 及 16x16 也可以减少循环次数。我觉得这里主要的问题是 e64 是否被支持，因为根据 RVV Spec，VLEN 必须 >= 128，且 LMUL 2 必须支持，但似乎没有规定 SEW 是否必须支持 64。如果硬件不支持将会被 Trap。
2. Neon 的实现我在开始写之前也看了，我觉得他们主要就是把 `memcpy(3)` 给换成了两条 SIMD Unit-stride 访存指令，而 Stride 还是他们自己通过指针运算来实现的。这我觉得优化力度或许不够，因为尽管它可以 eliminate 函数访问带来的 overhead，但 RVV 本身提供 Strided 访存，正好适合这种场景。
3. 我这边写过 fuzz，这三个函数的结果应该都是正确的（至少在我给定的随机数据及参数范围内）。

**Comment by sunmin89** [comment]
> ~啊抱歉这两天一直在 RVSC 所以没看 GitHub~
> 
> 刚爬完了楼，主要是这样几点吧：
>  ...



哇，点赞！我对这一块就是理解的模模糊糊的，瞬间治好了两个月来的腰疼!

关于性能，汪老师之前说的通过指令数来对比，方法应该是对的，毕竟目前的硬件实在是太少了

**Comment by unicornx** [comment]
讨论先到这里吧，我先 close 这个 issue。
