### ISSUE TITLE
有关 rvv 头文件的包含

### ISSUE THREAD

**Issue by unicornx** [aosp-riscv/libvpx#14]
参考 <https://github.com/riscv-non-isa/rvv-intrinsic-doc/releases/tag/draft-20230811-a810011071e9e2f630450f01f5fdc9a9ccc3e3be> 的 Chapter 3. Header file inclusion, 标准写法如下：
```cpp
#ifdef __riscv_v_intrinsic
#include <riscv_vector.h>
#endif /* __riscv_v_intrinsic */
```
`__riscv_v_intrinsic` 是 gcc 中 builtin 的一个宏，可以用来判断当前你使用的 gcc 是否支持 rvv 以及通过该值可以知道你使用的 gcc 支持的 rvv 的版本 （参考 Chapter 2. Test macro）
如果 gcc 是我们自己构建的，我们也可以从 gcc 的源码中获取这个值，具体源码是：`gcc/config/riscv/riscv-c.cc` 中的 `riscv_cpu_cpp_builtins()` 函数:
```cpp
if (TARGET_MIN_VLEN)
    {
      builtin_define ("__riscv_vector");
      builtin_define_with_int_value ("__riscv_v_intrinsic",
                                     riscv_ext_version_value (0, 11));
    }
```
“11” 说明当前 gcc 符合 rvv c intrinsic 标准 "0.11"。因为 rvv c intrinsic 的规范还在快速演进中，我们测试时需要特别注意这个问题。

**Comment by sunmin89** [comment]
> 参考 https://github.com/riscv-non-isa/rvv-intrinsic-doc/releases/tag/draft-20230811-a810011071e9e2f630450f01f5fdc9a9ccc3e3be 的 Chapter 3. Header file inclusion, 标准写法如下：

感谢提醒，我注意到这个了，但是还没有细看 

另外我有一个疑问，这个 draft pdf 中，的隐式/显示，重载/非重载到底有啥区别呀？ 

![image](https://github.com/aosp-riscv/libvpx/assets/17847861/3e053d0f-daef-45cd-873b-6429890d7c88)

平头哥只列出了 Appendix - Explicit (Non Overloaded) intrinsics
参见，https://xuantie.t-head.cn/community/download?id=4090445921563774976

**Comment by unicornx** [comment]
> > 参考 https://github.com/riscv-non-isa/rvv-intrinsic-doc/releases/tag/draft-20230811-a810011071e9e2f630450f01f5fdc9a9ccc3e3be 的 Chapter 3. Header file inclusion, 标准写法如下：
> 
> 感谢提醒，我注意到这个了，但是还没有细看
> 
> 另外我有一个疑问，这个 draft pdf 中，的隐式/显示，重载/非重载到底有啥区别呀？
> 
> ![image](https://user-images.githubusercontent.com/17847861/261989067-3e053d0f-daef-45cd-873b-6429890d7c88.png)
> 
> 平头哥只列出了 Appendix - Explicit (Non Overloaded) intrinsics 参见，https://xuantie.t-head.cn/community/download?id=4090445921563774976

我理解只是两种不同的写法

**Comment by unicornx** [comment]
closed due to I'm not working on this now.
