### ISSUE TITLE
add rvv support framework

### ISSUE THREAD

**Issue by unicornx** [aosp-riscv/libvpx#8]
参考 https://chromium-review.googlesource.com/c/webm/libvpx/+/3404064

**Comment by unicornx** [comment]
有关 RunTime Cpu Detection(RTCD) 的疑问

我搜索了代码，感觉 rtcd 的功能似乎并没有被用上啊，FIXME

configure 时带上 “--enable-runtime-cpu-detect” 会 enable 这个 feature，默认是 disabled。（`#define CONFIG_RUNTIME_CPU_DETECT 0` in `vpx_config.h`）

以 arm 的 neon 处理为例（`arm_cpu_caps()`）

有两处会触发 RTCD 的调用。

## 第一处是在诸如 make 自动生成的 `vpx_dsp_rtcd.h`/`vp9_rtcd.h`/`vp8_rtcd.h`/`vpx_scale_rtcd.h` 中

以 vp8 为例 `vp8_rtcd.h`，这里调用的 `vp8_rtcd()` 会在以下地方被调用：
- 编码：vp8e_init -> vp8_rtcd 
- 解码：vp8_init -> vp8_rtcd

`vp8/common/rtcd.c` 中定义了 `vp8_rtcd()`
```cpp
void vp8_rtcd() { once(setup_rtcd_internal); }
```
这么做保证这里 `setup_rtcd_internal()` 只会被执行一次
但这里并返回值并没有被使用，感觉起到了什么作用么？

setup_rtcd_internal 根据 ARCH 的不同调用不同的函数， 以 arm 为例：
```cpp
static void setup_rtcd_internal(void)
{
    int flags = arm_cpu_caps();

    (void)flags;

}
```

## 还有另外一种情况会触发检测：而且只针对 v8

对于 v8，会在初始化部分检测当前 target 的 capability

- 解码部分：vp8_decode -> vp8_create_decoder_instances -> create_decompressor 
- 编码部分：vp8e_init -> vp8_create_compressor 

以上两者最终都会走到以下逻辑：
vp8_create_common -> vp8_machine_specific_config -> 
这里会给 ctx->cpu_caps 赋值的，但搜了一下，似乎也没有使用 ctx->cpu_caps 的地方

## 结论

FIXME：所以我理解目前 RTCD 只是一个空架子，没有真正被使用上。

**Comment by sunmin89** [comment]
我也有同样的困惑

**Comment by unicornx** [comment]
closed with PR #9
